### PR TITLE
add open source decompiler link

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by bradsdavis** [comment]
Is this actually a full decompiler or just disassembler?  In other words, is it a "back to source" decompiler?

Java ships with a disassembler: javap
http://docs.oracle.com/javase/1.5.0/docs/tooldocs/windows/javap.html

**Comment by ysangkok** [comment]
Yeah, they are both full decompilers. I tried them out today and yesterday, and they work pretty well, at least as well as JD-GUI. You should try them out :) Krakatou is a lot slower than Procyon, maybe it's faster in Pypy. It is also not pattern matching, which is interesting. I reported a couple of bugs on both of them, the developers are very responsive.

**Comment by ysangkok** [comment]
There is also [Dava](http://www.sable.mcgill.ca/dava/), which is also FOSS. It looks like it was one of those "imma get a master's thesis and then forget this" projects, though.

**Comment by bradsdavis** [comment]
JD-Decompiler isn't open source.  But it is great.
Dava isn't full-featured.  Trying to link to relevant alternatives for people.

**Comment by ysangkok** [comment]
The two FOSS decompilers are linked are relevant alternatives. I know JD-GUI is not FOSS, I was mentioning it to describe to you the quality of the open source implementations linked. I'd leave Dava out too. But why not include the two I suggested?

**Comment by Storyyeller** [comment]
For what it's worth, you can speed up Krakatau by running Python with -o to disable assertions.

**Pull request merged**
